#! /bin/bash

msg_print(){
    echo -e "`date +'%F %T.%N' | cut -c 1-23` $1"
}

msg(){
    case $1 in
        d|done)       msg_print "INFO: $2"      &&  exit   0 ;;
        e|error)      msg_print "ERROR: $2"     &&  exit   1 ;;
        i|info)       msg_print "INFO: $2"      &&  return 0 ;;
        w|warning)    msg_print "WARNING: $2"   &&  return 0 ;;
        h|hello)      msg_print "Hello world"   &&  return 0 ;;
        a|attention)  msg_print "ATTENTION: $2" &&  return 0 ;;
    esac
}

Time(){
    case $1 in
        Point)
            timepoint_f="`mktemp $TEMP/XXXXXXXXXXXX`"

            case $2 in
                a|start)    echo "`date +%s`" >  $timepoint_f   ;;
                b|stop)     echo "`date +%s`" >> $timepoint_f   ;;
                c|used)
                            echo "`tail -1 $timepoint_f` - `head -1 $timepoint_f`" | bc
                            remove $timepoint_f
                            ;;
            esac
            ;;
    esac
}

GitSubmoduleUpdate(){
    msg i "Start git submodule update"
    git submodule update --init --recursive
}
