#! /bin/bash

CONFIG_DIR=$(dirname $0)

case `uname -s` in
    Darwin)
        NODE_OS="OSX"
        TMP_DIR=/tmp/jenkins
        
        BIN_SED=/usr/local/bin/sed
        BIN_MD5=md5
        ;;
    Linux)
        NODE_OS="`uname -s`"
        TMP_DIR="/dev/shm/jenkins"

        BIN_SED=sed
        BIN_MD5=md5sum
        ;;
esac

test -d $TMP_DIR || mkdir -p $TMP_DIR

BUILD_LOG=$JENKINS_HOME/jobs/$JOB_NAME/builds/$BUILD_NUMBER/log

test -f "$BUILD_LOG" && BUILD_USER=`head -1 $BUILD_LOG | awk -F '0m' '{print $2}'`

APP_PRJ="`echo $JOB_NAME | awk -F '_' '{print $1}'`"
APP_OBJ="`echo $JOB_NAME | awk -F '_' '{print $2}'`"
APP_ENV="`echo $JOB_NAME | awk -F '_' '{print $3}'`"
APP_ACT="`echo $JOB_NAME | awk -F '_' '{print $4}'`"
APP_TGT="`echo $JOB_NAME | awk -F '_' '{print $5}'`"
  
app_env="`echo $APP_ENV  | tr A-Z a-z`"

# COMPANY info
COMPANY_NAME_EN=""

### Jenkins
    JKS_RUN_USER=
      JKS_DL_URL=
JKS_DOWNLOAD_URL=$JKS_DL_URL
      JKS_DL_DIR=

# OSX Auth
OSX_KEYCHAIN_AUTH_FILE=$CONFIG_DIR/auth/osx-keychain.auth
     OSX_KEYCHAIN_FILE=~jenkins/Library/Keychains/login.keychain

### Android
ANDROID_SDK_LOCAL_FILE=$CONFIG_DIR/project/$APP_PRJ/Android/local.properties

ANDROID_APK_DIR=app/build/outputs/apk
ANDROID_APK_SAVE_URL=Android/apk/`date +%Y/%m/%d`
ANDROID_APK_SAVE_DIR=$JKS_DL_DIR/$ANDROID_APK_SAVE_URL

ANDROID_PRE_IM_UPLOAD_KEY=
ANDROID_PRE_IM_UPLOAD_URL=


### iOS
iOS_IPA_SAVE_URL=iOS/ipa/`date +%Y/%m/%d`
iOS_IPA_SAVE_DIR=$JKS_DL_DIR/$iOS_IPA_SAVE_URL

                 iOS_DEV_CSI=""
iOS_DEV_PROVISIONING_PROFILE=""


# Gradle
GRADLE_PROPERTIES=$(dirname $ANDROID_SDK_LOCAL_FILE)/gradle.properties

###
    PING_SET="sudo sysctl -w net.ipv4.icmp_echo_ignore_all"
 PING_ENABLE="$PING_SET=0"
PING_DISABLE="$PING_SET=1"

### Docker
DOCKER_TAG=latest
DOCKER_HUB=
DOCKER_REPOSITORY=$DOCKER_HUB
DOCKER_BUILD_HOST=
DOCKER_BUILD_PATH=$(dirname $WORKSPACE)/${APP_PRJ}_${APP_OBJ}_${APP_ENV}_${APP_ACT}_Docker
DOCKER_BUILD_TO_RUN_LIST=$TMP_DIR/docker_build_list-$APP_PRJ-$APP_OBJ-$APP_ENV

# Default Settings
 SSH_USER=
 SSH_PORT=
 SSH_OPTS=

SCP_SPEED=51200
 WEB_ROOT=
HTTP_PORT=80

# Nginx Status URL
 NGX_STAT=/nginx_status

# Nginx 
  NGX_DIR=/usr/local/nginx
 NGX_SBIN=$NGX_DIR/sbin/nginx

# CURL
         NGX_CC_CT=2
      NGX_CC_RETRY=2
   NGX_CC_MAX_TIME=1
NGX_CC_RETRY_DELAY=1

# nginx_stat_check
NSC_HTTP_PORT=80
 NSC_HTTP_URL="/"

# Users Chack
 PERMISSION_DIR_USERS=$CONFIG_DIR/permission/users
PERMISSION_DIR_GROUPS=$CONFIG_DIR/permission/groups

ALWAYS_ALLOWED_GROUPS="ops-core"

mf=$CONFIG_DIR/modules

if [ -f "$mf" ]
then
    . $mf
else
    echo -e "Error: $mf does not exist"
    exit 1
fi
