#! /bin/bash

msg_print(){
    echo -e "`date +'%F %T.%N' | cut -c 1-23` $1"
}

msg(){
    case $1 in
        d|done)       msg_print "INFO: $2"      &&  exit   0 ;;
        e|error)      msg_print "ERROR: $2"     &&  exit   1 ;;
        i|info)       msg_print "INFO: $2"      &&  return 0 ;;
        w|warning)    msg_print "WARNING: $2"   &&  return 0 ;;
        h|hello)      msg_print "Hello world"   &&  return 0 ;;
        a|attention)  msg_print "ATTENTION: $2" &&  return 0 ;;
    esac
}
