#! /bin/bash

NAMESPACE=$app_prj
 APP_NAME="${CNES}_$app_sub"
 WEB_ROOT="$GFS_FILES_DIR/$app_prj/$app_env/$ENVIRONMENT_ID/$APP_NAME"
 TEMPLATE="/data/dockerfiles/$app_prj/$app_env/$APP_SUB"

JobActionController(){
    load base
    load file
    load check
    load ssh
    load docker
    load kubectl

    POD_CONFIG="Dockerfiles/Job.yaml"
      
    test -f $POD_CONFIG && sudo kubectl delete -f $POD_CONFIG

    remove Dockerfiles

    DockerfilesCopy
    sed -i "s#JOB_TARGET_VALUE#$TARGET#" $POD_CONFIG

    KubectlPSCD
}
