#! /bin/bash

JobActionController(){
    load base
    load file
    load check
    load ssh
    load docker
    load kubectl

    POD_CONFIG="$DOCKER_TEMPLATE_DN/Job.yaml"

    test -f $POD_CONFIG && kubectl delete -f $POD_CONFIG

    DockerfileInit

    sed -i "s#JOB_TARGET_VALUE#$TARGET#" $POD_CONFIG

    KubeController
}
