#! /bin/bash

NAMESPACE=
 APP_NAME=""
 WEB_ROOT="$GFS_FILES_DIR/$app_prj/$app_env/$ENVIRONMENT_ID/$APP_NAME"

JobActionController(){
    load base
    load file
    load check
    load ssh
    load docker
    load kubectl

    POD_CONFIG="Job.yaml"

    test -f $POD_CONFIG && sudo kubectl delete -f $POD_CONFIG

    DockerfileInit

    sed -i "s#JOB_TARGET_VALUE#$TARGET#" $POD_CONFIG

    KubeController
}
