#! /bin/bash

### Default Settings
# eg.: node-qa
#PROJECT_NAME="$app_prj-$APP_SUB-$SERVER_ID"

NAMESPACE="$app_prj-$app_env"
test -z "$APP_NAME"     && APP_NAME="$APP_SUB"
test -z "$REPLICAS_NUM" && REPLICAS_NUM=1

KubectlGet(){
    case $1 in
        svc|SVC)    kubectl get svc          -n $NAMESPACE ;;
        deploy)     kubectl get deploy       -n $NAMESPACE ;;
        rs|RS)      kubectl get rs   -o wide -n $NAMESPACE ;;
        pods|Pods)  kubectl get pods -o wide -n $NAMESPACE ;;
        ClusterIP)  KubectlGet SVC | awk '{print $3}'      ;;
    esac
}

KubeController(){
    load replace

     f_rc="Deployments.yaml"
    f_svc="Service.yaml"

    check file $f_rc

    test -f $f_rc  && f_lists="$f_rc"
    test -f $f_svc && f_lists="$f_lists $f_svc"

    ReplaceKubeFile

    DockerfileBackup

    if [ -f $f_svc ]
    then
        msg i "Check service $PROJECT_NAME"
        KubectlGet SVC | grep -q "^$PROJECT_NAME "

        if [ $? = 0 ]
        then
            msg a "Service $PROJECT_NAME already exist"
        else
            msg a "Create $PROJECT_NAME"
            kubectl create -f $f_svc
        fi
    fi

    msg i "Check deployment $PROJECT_NAME"
    KubectlGet deploy | grep -q "$PROJECT_NAME"

    if [ $? = 0 ]
    then
        #msg a "Update deployment $PROJECT_NAME image to $DOCKER_IMAGE_NAME:$DOCKER_TAG"
        #kubectl set image deploy/$PROJECT_NAME $PROJECT_NAME=$DOCKER_IMAGE_NAME:$DOCKER_TAG -n $NAMESPACE

        #kubectl apply -f $f_rc

        msg i "Update deployment $PROJECT_NAME"
        kubectl delete -f $f_rc
        kubectl create -f $f_rc
    else
        msg a "Create deployment $PROJECT_NAME"
        kubectl create -f $f_rc
    fi

    test $? = 0 && msg d "Successfully completed"
}
