#! /bin/bash

# Change owner to nobody
WRITE_DIRS="data"

APP_PORT=80
APP_NAME="${CNES}_${APP_SUB}"

WEBActionAdapter(){
    load base
    load file
    load check
    load ssh
    load docker
    load kubectl

    SSH_HOST="$GFS_HOST"
    SSH_USER="root"
    RUN_USER="nobody"
    OWN_USER="$RUN_USER:$RUN_USER"
    RSC_OPTS="-av --exclude-from=$RSYNC_EXCLUDE_LIST"
    WEB_ROOT="$GFS_FILES_DIR/$app_prj/$app_env/$ENVIRONMENT_ID/$APP_NAME"

    ### NOTE: Disabled by composer ERROR, 2017-07-19
    # Composer Check
    #ComposerCheck

    if [ "$SKIP_UPLOAD" != "true" ]
    then
        SSH "test -d $WEB_ROOT || mkdir -p $WEB_ROOT"

        msg i "准备同步至 GlusterFS: $WEB_ROOT"

        rsync $RSC_OPTS . $SSH_USER@$SSH_HOST:$WEB_ROOT

        msg i "更改文件权限"

        SSH "chown -R root:root $WEB_ROOT"
    else
        msg i "没有文件需要上传"
    fi

    if [ ! -z "$CACHE_DIRS" ]
    then
        msg i "清除缓存目录: $CACHE_DIRS"
        for d in $CACHE_DIRS
        do
            SSH "rm -rf $WEB_ROOT/$d"
        done
    fi
    
    if [ ! -z "$WRITE_DIRS" ]
    then
        for nbd in $WRITE_DIRS
        do 
            msg i "检测是否存在文件夹 $nbd"
            SSH "test -d $WEB_ROOT/$nbd && chown -R nobody:nobody $WEB_ROOT/$nbd"
        done
    fi 

    if [ "$RESTART_CONTAINER" = "true" ]
    then
        DockerfileCopy

        KubectlPSCD
    else
        msg d "成功更新"
    fi
}
